// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBv1EKn4E2P8wr0xYMlKUBKkWPHEIQGg',
    appId: '1:1017287457565:web:8b7780c23e45f1b6acfff4',
    messagingSenderId: '1017287457565',
    projectId: 'chatapp-365da',
    authDomain: 'chatapp-365da.firebaseapp.com',
    storageBucket: 'chatapp-365da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8u33-vhNTy_IVsp-JF0ucY639JjVK6o',
    appId: '1:1017287457565:android:dc192a6eec393692acfff4',
    messagingSenderId: '1017287457565',
    projectId: 'chatapp-365da',
    storageBucket: 'chatapp-365da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuBSSoMZ5EWftQyMa3zCL_uv3vqVa2rGE',
    appId: '1:1017287457565:ios:53a8ad187e1b72b7acfff4',
    messagingSenderId: '1017287457565',
    projectId: 'chatapp-365da',
    storageBucket: 'chatapp-365da.appspot.com',
    iosClientId: '1017287457565-6mopglv25cck00uq29odj5ruab34p6b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedManuallyPrac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuBSSoMZ5EWftQyMa3zCL_uv3vqVa2rGE',
    appId: '1:1017287457565:ios:e39c8aff7fd7c8aaacfff4',
    messagingSenderId: '1017287457565',
    projectId: 'chatapp-365da',
    storageBucket: 'chatapp-365da.appspot.com',
    iosClientId: '1017287457565-1fufbum08gse0jkuli8l7tbj1ai9goed.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedManuallyPrac.RunnerTests',
  );
}
