// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjh4GNSIe9Sq65ZgpJWmNVfcNijpY3WIU',
    appId: '1:340457607684:web:841d5969dbe6593aa81b51',
    messagingSenderId: '340457607684',
    projectId: 'chatapp-58d66',
    authDomain: 'chatapp-58d66.firebaseapp.com',
    storageBucket: 'chatapp-58d66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPZyeBD2Nq6wSWYHCJvWa_QhJkmlloeVM',
    appId: '1:340457607684:android:09c0a78ae492c013a81b51',
    messagingSenderId: '340457607684',
    projectId: 'chatapp-58d66',
    storageBucket: 'chatapp-58d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_nPOqQXPgWh4ho51HgoMUoL8Nkq3vO7A',
    appId: '1:340457607684:ios:31a3b435dbacaaa1a81b51',
    messagingSenderId: '340457607684',
    projectId: 'chatapp-58d66',
    storageBucket: 'chatapp-58d66.appspot.com',
    iosClientId: '340457607684-0tihtrl1082s8gm5bglcn74bblcuq57g.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedManuallyPrac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_nPOqQXPgWh4ho51HgoMUoL8Nkq3vO7A',
    appId: '1:340457607684:ios:8ab38e112b0b4681a81b51',
    messagingSenderId: '340457607684',
    projectId: 'chatapp-58d66',
    storageBucket: 'chatapp-58d66.appspot.com',
    iosClientId: '340457607684-7663h7mntqo9ilphbrve9qvjl4ntu77t.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackedManuallyPrac.RunnerTests',
  );
}
